### ISSUE TITLE
Update tools to "Barbossa"

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-odroid-xu4#8]
This is the task list to update to update the XU4 repo to v0.8.0 Barbossa like the image-builder-rpi repo. We should do this in multiple small pull requests. The [image-builder-rpi repo](https://github.com/hypriot/image-builder-rpi) should be used as a base to look how we want to structure all the steps.

There is no specific order. We can add simple things first and create a lower pre-release version <0.8.0.
- [x] rename to hypriotos-odroid-xu4-vX.X.X.img.zip, fixed with #10 by @mevatron 
- [x] update docker-compose, #12
- [x] update docker-machine, #12
- [x] update docker-engine, #12
- [x] update rootfs, #12
- [ ] update device-init
- [ ] install docker images for consul + swarm
- [ ] install cluster-lab
- [ ] check for a more up to date kernel > 3.10
- [ ] add FAT partition for flash / device-init, do we need some similar tar like for rpi in image-builder-raw repo?

**Comment by mevatron** [comment]
@StefanScherer I found there is a 4.2 kernel available [here](https://github.com/tobetter/linux). However, it looks like it may have some [issues](https://github.com/tobetter/linux/issues).

Is it worth upgrading to 4.2 with these issues in mind? If so, do you have an odroid-kernel repo similar to your rpi-kernel Vagrant box?

Will

**Comment by StefanScherer** [comment]
@mevatron Sounds interesting. Is there a precompiled version? No we haven't a kernel repo for ODROID. I don't know how much effort that would take to adapt the build.

I've tried to update some Docker tools today and build an 0.2.0 SD image. But I had problems booting it. Have you tried that image?

**Comment by mevatron** [comment]
@StefanScherer Just got a chance to try the build out. It seems to boot up just fine. Here are the versions:

```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.4.3
 Git commit:   5604cbe
 Built:        Mon May  9 00:50:14 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.4.3
 Git commit:   5604cbe
 Built:        Mon May  9 00:50:14 2016
 OS/Arch:      linux/arm
```

```
$ docker-compose -v
docker-compose version 1.7.1, build 6c29830
```

```
$ docker-machine -v
docker-machine version 0.7.0, build a650a40
```

What errors did you run into booting it?

**Comment by StefanScherer** [comment]
@mevatron Great! I have to try it again. The device did nothing after inserting the SD card, but as it works for you it was a PEBCAK :-)

**Comment by mevatron** [comment]
@StefanScherer Ha! They do happen sometimes :) You might check the little switch on the back next to the HDMI port, see if its set on uSD instead of eMMC. That one got me when I first booted it to the SD card :)

**Comment by StefanScherer** [comment]
@mevatron Yes, the switch wasn't excactly in the uSD end position, a little bit in between. Now the XU4 boots and works well. :-)
